warning off all;
clc;
clear all;
close all;

FigWin = figure('Position',[50 50 650 500],'Name','EatIT-Calorie Prediction Application',...
                 'NumberTitle','off','Color',[ 0.82 0.81 0.77 ]);

AxesHandle = axes('Position',[0.25 0.15 0.65 0.75], 'Box','on');

imageLoad='INPUT IMAGE';
h=uicontrol(FigWin,'Style','pushbutton','Position',[40,420,80,20],...
             'String','LOAD','Callback',['I=loadimage;' 'imagesc(I);'...
             'title(imageLoad);' 'colormap(gray);']);

         
clusteredimage='CLUSTERED IMAGE';
h=uicontrol(FigWin,'Style','pushbutton','Position',[40,400,80,20],...
             'String','CLUSTER','Callback',['I_cluster_1=cluster(I);'... 
             'subplot(AxesHandle);' 'imagesc(I_cluster_1);'...
             'title(clusteredimage);' 'colormap(gray);']);       
         
                  
gimage='GRAY IMAGE';
h=uicontrol(FigWin,'Style','pushbutton','Position',[40,380,80,20],...
             'String','GRAY','Callback',['gim=grayimage(I);'... 
             'subplot(AxesHandle);' 'imagesc(gim);'...
             'title(gimage);' 'colormap(gray);']);
 
fil_image='FILTERED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,360,80,20],...
                'String','FILTERED','Callback',['enhf=fil_en(gim);'...
                'subplot(AxesHandle);' 'imagesc(enhf);'...
                'title(fil_image);' 'colormap(gray);']);

con_image='CONTRAST ENANCED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,340,80,20],...
                'String','CONTRAST','Callback',['[enh rows columns]=his_en(gim);'...
                'subplot(AxesHandle);' 'imagesc(enh);'...
                'title(con_image);' 'colormap(gray);']);
                        
edge_image='EDGE DETECTED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,320,80,20],...
                'String','CANNY','Callback',['edg=edgedet(enhf);'...
                'subplot(AxesHandle);' 'imagesc(edg);'...
                'title(edge_image);' 'colormap(gray);']);            
                        
bin_image='BINARY IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,300,80,20],...
                'String','BINARY','Callback',['bin=binaryimg(gim);'...
                'subplot(AxesHandle);' 'imagesc(bin);'...
                'title(bin_image);' 'colormap(gray);']); 

seg_image='SEGMENTED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,280,80,20],...
                'String','SEGMENTED','Callback',['heIbin=segimg(enh);'...
                'subplot(AxesHandle);' 'imagesc(heIbin);'...
                'title(seg_image);' 'colormap(gray);']); 
                  
lbp_image='FEATURE EXTRACTED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,260,80,20],...
                'String','LBPFEAT','Callback',['[localBinaryPatternImage]=lbp(enh);'...
                'subplot(AxesHandle);' 'imagesc(localBinaryPatternImage);'...
                'title(lbp_image);' 'colormap(gray);']);
                                    
shape_image='SHAPE DETECTED IMAGE';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,240,80,20],...
                'String','SHAPE DET','Callback',['[feature angle magnitude Im] = hog_feature_vector(gim);'...
                'subplot(AxesHandle);' 'imagesc(uint8(magnitude));'...
                'title(shape_image);' 'colormap(gray);']);
            
                        
feature_value='FEATURE VALUE CALCULATION';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,220,80,20],...
                'String','FEATURE VALUE','Callback',['[mAR mMIN mMAJ]=featuree(Im);'...
                'subplot(AxesHandle);' 'imagesc(uint8(magnitude));'...
                'title(feature_value);' 'colormap(gray);']);

feature_inp='FEATURE INPUT';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,200,80,20],...
                'String','FEATURE INPUT','Callback',['[TrainingSet GroupTrain TestSet]=featinp(mAR);'...
                'subplot(AxesHandle);' 'imagesc(uint8(magnitude));'...
                'title(feature_inp);' 'colormap(gray);']);
            
class_image='CALORIE MEASUREMENT';
h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,180,80,20],...
                'String','CALORIE','Callback',['[result]=multisvm(TrainingSet,GroupTrain,TestSet,mAR);']);                    


h=uicontrol(FigWin, 'Style','pushbutton','Position',[40,160,80,20],...
                'String','EXIT','Callback',['exit;']);
%             
